#!/usr/bin/env python
# ─────────────────────────────────────────────────────────────────────────────
# rank.py — Redrob Hackathon Submission Ranker
#
# Produces the top-100 submission CSV from candidates.jsonl.
# Must complete in ≤5 minutes on CPU, ≤16 GB RAM, no network.
#
# Reads precomputed artifacts from data/precomputed/ (generated by precompute.py).
# Falls back to pure behavioral scoring if LLM artifacts are unavailable.
#
# Usage:
#   python rank.py --candidates candidates.jsonl --out submission.csv
#   python rank.py --candidates candidates.jsonl --out submission.csv --top-n 100
# ─────────────────────────────────────────────────────────────────────────────

import argparse
import csv
import json
import logging
import sys
import time
from pathlib import Path

# ── Path setup ────────────────────────────────────────────────────────────────
_ROOT = Path(__file__).resolve().parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("rank")

PRECOMPUTED_DIR = _ROOT / "data" / "precomputed"
BEHAVIORAL_FILE = PRECOMPUTED_DIR / "behavioral_scores.json"
EMBEDDING_FILE  = PRECOMPUTED_DIR / "embedding_shortlist.json"
LLM_SCORES_FILE = PRECOMPUTED_DIR / "llm_scores.json"


# ─────────────────────────────────────────────────────────────────────────────
# Score fusion
# ─────────────────────────────────────────────────────────────────────────────

# Composite weights — LLM scores carry the most weight for evidence quality
# Behavioral provides the floor and catches honeypots/consulting-only profiles
LLM_WEIGHT        = 0.65   # Evidence-grounded Q&A + parallel passes
BEHAVIORAL_WEIGHT = 0.25   # Deterministic feature scoring
EMBEDDING_WEIGHT  = 0.10   # BGE-small cosine similarity vs JD rubric


def fuse_scores(
    behavioral: float,
    embedding: float,
    llm: float | None,
    is_honeypot: bool,
    excluded_by_llm: bool,
) -> float:
    """
    Produce final 0–1 composite score.

    - Honeypots → 0.0 (always excluded from top 100)
    - LLM-excluded (failed hard gate) → score × 0.10 (audit only)
    - LLM scored → weighted blend of all three layers
    - Behavioral only → behavioral × 0.90 + embedding × 0.10
    """
    if is_honeypot:
        return 0.0

    if llm is not None:
        base = llm / 10.0  # LLM scores are 0–10, normalise to 0–1
        fused = (
            base * LLM_WEIGHT
            + behavioral * BEHAVIORAL_WEIGHT
            + embedding * EMBEDDING_WEIGHT
        )
        if excluded_by_llm:
            fused *= 0.10   # Hard gate failure — penalise heavily, don't discard
        return round(min(fused, 1.0), 6)
    else:
        # Behavioral + embedding only (no LLM coverage for this candidate)
        return round(min(
            behavioral * 0.90 + embedding * 0.10,
            1.0
        ), 6)


# ─────────────────────────────────────────────────────────────────────────────
# Reasoning generation
# ─────────────────────────────────────────────────────────────────────────────

def build_reasoning(
    beh: dict,
    llm: dict | None,
    final_score: float,
) -> str:
    """
    Generate a 1–2 sentence reasoning string that is:
    - Specific to the candidate's actual profile
    - Grounded in the strongest evidence we have
    - Not templated (Stage 4 penalises identical/template reasoning)
    """
    title   = beh.get("current_title", "")
    yoe     = beh.get("years_of_experience", 0)
    company = beh.get("current_company", "")
    loc     = beh.get("location", "")

    # Lead with the strongest differentiating signal
    parts: list[str] = []

    if llm:
        # Use the top LLM criterion score as the lead evidence
        criterion_scores = llm.get("criterion_scores", [])
        top_cs = sorted(criterion_scores, key=lambda c: c.get("score", 0), reverse=True)

        if top_cs:
            best = top_cs[0]
            score_val = best.get("score", 0)
            criterion_text = best.get("criterion_text", "")
            evidence = best.get("evidence_quote", "")
            answer = best.get("answer", "")

            if score_val >= 7 and evidence and evidence != "NO_EVIDENCE_FOUND":
                # Strong evidence quote — use it directly
                evidence_short = evidence[:100].strip()
                parts.append(
                    f"{title} with {yoe:.0f} yrs exp; "
                    f"strong on '{criterion_text}': \"{evidence_short}\""
                )
            elif answer:
                answer_short = answer[:120].strip()
                parts.append(f"{title} ({yoe:.0f} yrs, {company}); {answer_short}")
            else:
                parts.append(f"{title} with {yoe:.0f} yrs; based at {loc}")

        # Add red flags if any
        red_flags = llm.get("red_flags", [])
        if red_flags:
            flag = red_flags[0]
            sev = flag.get("severity", "info")
            detail = flag.get("detail", "")[:80]
            if sev == "concern":
                parts.append(f"Note: {detail}")

        # Add gate failure reason if excluded
        if llm.get("excluded") and llm.get("exclusion_reason"):
            reason = llm["exclusion_reason"][:80]
            parts.append(f"Hard gate failure: {reason}")

        # Add open signal if strong
        open_signals = llm.get("open_signals", [])
        if open_signals and len(parts) < 2:
            sig = open_signals[0].get("signal", "")[:80]
            parts.append(sig)

    else:
        # Behavioral-only reasoning
        skill_score  = beh.get("skill_match_score", 0)
        career_score = beh.get("career_quality_score", 0)
        neg_signals  = beh.get("negative_signals", [])

        skill_label = (
            "strong AI/ML skills" if skill_score >= 0.7
            else "moderate AI/ML skill coverage" if skill_score >= 0.4
            else "limited AI/ML skill signals"
        )
        career_label = (
            "product-company background" if career_score >= 0.6
            else "mixed career background" if career_score >= 0.3
            else "services-heavy background"
        )
        parts.append(
            f"{title} with {yoe:.0f} yrs exp at {company}; "
            f"{skill_label}, {career_label}"
        )
        if neg_signals:
            parts.append(neg_signals[0][:80])

    reasoning = "; ".join(p.strip(".") for p in parts if p.strip())
    # Ensure it ends with a period and is not too long
    if not reasoning.endswith("."):
        reasoning += "."
    return reasoning[:300]


# ─────────────────────────────────────────────────────────────────────────────
# Main ranking logic
# ─────────────────────────────────────────────────────────────────────────────

def rank(candidates_path: Path, top_n: int = 100) -> list[dict]:
    t_start = time.time()

    # ── Load precomputed artifacts ────────────────────────────────────────────
    logger.info("Loading precomputed artifacts...")

    if not BEHAVIORAL_FILE.exists():
        logger.error(
            f"Behavioral scores not found: {BEHAVIORAL_FILE}\n"
            "Run: python precompute.py --candidates <path> --skip-llm"
        )
        sys.exit(1)

    behavioral_records = json.loads(BEHAVIORAL_FILE.read_text(encoding="utf-8"))
    logger.info(f"  Behavioral scores: {len(behavioral_records):,} candidates")

    embedding_map: dict[str, float] = {}
    if EMBEDDING_FILE.exists():
        emb_list = json.loads(EMBEDDING_FILE.read_text(encoding="utf-8"))
        embedding_map = {r["candidate_id"]: r["embedding_score"] for r in emb_list}
        logger.info(f"  Embedding shortlist: {len(embedding_map):,} candidates")
    else:
        logger.warning("  Embedding shortlist not found — using 0.5 default for all")

    llm_scores: dict[str, dict] = {}
    if LLM_SCORES_FILE.exists():
        llm_scores = json.loads(LLM_SCORES_FILE.read_text(encoding="utf-8"))
        logger.info(f"  LLM scores: {len(llm_scores):,} candidates")
    else:
        logger.warning("  LLM scores not found — falling back to behavioral + embedding only")

    # ── Fuse scores for all candidates ────────────────────────────────────────
    logger.info("Fusing scores...")

    ranked: list[dict] = []
    for beh in behavioral_records:
        cid          = beh["candidate_id"]
        is_honeypot  = beh.get("is_honeypot", False)
        behavioral   = beh.get("composite_score", 0.0)
        embedding    = embedding_map.get(cid, 0.5)   # 0.5 = neutral if not in shortlist
        llm          = llm_scores.get(cid)
        llm_score    = llm["final_score"] if llm else None
        excluded_llm = llm["excluded"] if llm else False

        final = fuse_scores(
            behavioral=behavioral,
            embedding=embedding,
            llm=llm_score,
            is_honeypot=is_honeypot,
            excluded_by_llm=excluded_llm,
        )

        ranked.append({
            "candidate_id": cid,
            "score": final,
            "behavioral": behavioral,
            "embedding": embedding,
            "llm_score": llm_score,
            "is_honeypot": is_honeypot,
            "excluded_by_llm": excluded_llm,
            "_beh": beh,
            "_llm": llm,
        })

    # ── Sort: score descending, break ties by candidate_id ascending ──────────
    ranked.sort(key=lambda r: (-r["score"], r["candidate_id"]))

    # ── Take top_n (skip honeypots — they score 0.0 so naturally fall to bottom) ─
    top = [r for r in ranked if not r["is_honeypot"]][:top_n]

    # ── Verify non-increasing scores (submission spec §3) ─────────────────────
    for i in range(1, len(top)):
        if top[i]["score"] > top[i-1]["score"]:
            # Shouldn't happen after sort, but enforce explicitly
            top[i]["score"] = top[i-1]["score"]

    # ── Build output rows ─────────────────────────────────────────────────────
    output: list[dict] = []
    for rank_pos, r in enumerate(top, start=1):
        reasoning = build_reasoning(r["_beh"], r["_llm"], r["score"])
        output.append({
            "candidate_id": r["candidate_id"],
            "rank": rank_pos,
            "score": round(r["score"], 4),
            "reasoning": reasoning,
        })

    elapsed = time.time() - t_start
    logger.info(
        f"Ranking complete in {elapsed:.1f}s — "
        f"top candidate: {output[0]['candidate_id']} (score={output[0]['score']:.4f})"
        if output else "No candidates ranked"
    )

    # ── Honeypot guard check ──────────────────────────────────────────────────
    top_cids = {r["candidate_id"] for r in output}
    honeypots_in_top = sum(
        1 for beh in behavioral_records
        if beh["candidate_id"] in top_cids and beh.get("is_honeypot")
    )
    if honeypots_in_top > 0:
        logger.warning(
            f"WARNING: {honeypots_in_top} detected honeypots in top {top_n}. "
            f"Disqualification threshold is >10%. Run precompute.py to regenerate."
        )
    else:
        logger.info(f"Honeypot check: 0 honeypots in top {top_n} ✓")

    return output


# ─────────────────────────────────────────────────────────────────────────────
# Validation helpers
# ─────────────────────────────────────────────────────────────────────────────

def validate_output(rows: list[dict], top_n: int) -> bool:
    ok = True
    if len(rows) != top_n:
        logger.error(f"Expected {top_n} rows, got {len(rows)}")
        ok = False

    ranks = [r["rank"] for r in rows]
    if sorted(ranks) != list(range(1, top_n + 1)):
        logger.error("Ranks are not exactly 1 through 100")
        ok = False

    ids = [r["candidate_id"] for r in rows]
    if len(ids) != len(set(ids)):
        logger.error("Duplicate candidate_ids found")
        ok = False

    scores = [r["score"] for r in rows]
    for i in range(1, len(scores)):
        if scores[i] > scores[i-1] + 1e-9:
            logger.error(f"Score not non-increasing at rank {i+1}: {scores[i]} > {scores[i-1]}")
            ok = False
            break

    if ok:
        logger.info("Validation: PASSED ✓")
    return ok


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Redrob Hackathon — Submission ranker (≤5 min, CPU only)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python rank.py --candidates candidates.jsonl --out submission.csv
  python rank.py --candidates ./India_runs_data_and_ai_challenge/candidates.jsonl --out submission.csv
        """,
    )
    parser.add_argument(
        "--candidates",
        type=Path,
        default=Path("India_runs_data_and_ai_challenge/candidates.jsonl"),
        help="Path to candidates.jsonl",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("submission.csv"),
        help="Output CSV file path (default: submission.csv)",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=100,
        help="Number of candidates to rank (default: 100)",
    )
    parser.add_argument(
        "--no-validate",
        action="store_true",
        help="Skip output validation",
    )

    args = parser.parse_args()

    if not args.candidates.exists():
        logger.error(f"Candidates file not found: {args.candidates}")
        sys.exit(1)

    logger.info("=" * 60)
    logger.info("Redrob Hackathon — Submission Ranker")
    logger.info(f"Candidates : {args.candidates}")
    logger.info(f"Output     : {args.out}")
    logger.info(f"Top N      : {args.top_n}")
    logger.info("=" * 60)

    rows = rank(args.candidates, top_n=args.top_n)

    if not args.no_validate:
        validate_output(rows, args.top_n)

    # Write CSV
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["candidate_id", "rank", "score", "reasoning"],
            quoting=csv.QUOTE_ALL,
        )
        writer.writeheader()
        writer.writerows(rows)

    logger.info(f"Submission written → {args.out} ({len(rows)} rows)")

    # Quick preview
    logger.info("\nTop 5 candidates:")
    for r in rows[:5]:
        logger.info(f"  #{r['rank']:3d}  {r['candidate_id']}  {r['score']:.4f}  {r['reasoning'][:80]}")


if __name__ == "__main__":
    main()
